# Generated by Django 3.0.2 on 2020-04-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an article category (e.g. Sports)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the article', max_length=1000)),
                ('content', models.TextField(help_text='Enter the article content')),
                ('published_status', models.CharField(blank=True, choices=[('n', ' None'), ('nc', 'Needs Content'), ('nr', 'Needs Review'), ('a', 'Approved')], default='n', help_text='Article status', max_length=2)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.Author')),
                ('category', models.ManyToManyField(help_text='Select a genre for this book', to='rest_api.Category')),
            ],
        ),
    ]
